# Generated by Django 3.2.5 on 2022-06-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reverseString', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringtoreverse',
            name='otherPhrase',
        ),
    ]
